language: R
sudo: no
cache: packages
after_success: Rscript -e 'covr::coveralls(type = "all")'
warnings_are_errors: yes
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: --as-cran --install-args=--build
deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: biobankr*.t*gz
  'on':
    tags: yes
    repo: muschellij2/biobankr

